CREATE TABLE payments
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT   NOT NULL,
    amount        NUMERIC(12,2)    NOT NULL,
    status        VARCHAR(50)       NOT NULL,
    created_at    TIMESTAMP      NOT NULL,
    processed_at TIMESTAMP
);






