spring.application.name=notificationservice


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=orderuser
spring.rabbitmq.password=orderpass
management.health.rabbit.enabled=true