spring.application.name=orderservice

spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate


server.port=8081


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=orderuser
spring.rabbitmq.password=orderpass
management.health.rabbit.enabled=true

logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG