spring.application.name=orderservice

spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate

management.health.rabbit.enabled=false

server.port=8081